#!/usr/bin/env node
/**
 * Vision Clipping — .html redirect bridges.
 *
 * Every page now lives at a directory URL (/blog/foo/) and no URL on the site ends
 * in .html. Google, however, still has the old /blog/foo.html URLs in its index —
 * on 20 Aug 2026 they were the majority of our indexed pages. Letting them 404 would
 * drop those pages out of search before the new URLs are indexed.
 *
 * GitHub Pages cannot serve a 301, so each old path gets the strongest static
 * redirect that exists: canonical + instant meta refresh + location.replace().
 * Google follows all three and consolidates the old URL into the new one.
 *
 * These files are TEMPORARY. Once Search Console shows the directory URLs indexed
 * and the .html ones gone (check with `node ~/vision-seo/tools/gsc.mjs coverage`),
 * delete them: `node tools/redirect-bridges.mjs --clean`.
 *
 *   node tools/redirect-bridges.mjs          # write/refresh the bridges
 *   node tools/redirect-bridges.mjs --clean  # remove them all
 */
import { writeFileSync, unlinkSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SITE = 'https://vision-clipping.com';
const SKIP = new Set(['assets', 'uploads', '.git', '.github', 'tools', 'node_modules']);
export const MARKER = '<!-- redirect-bridge: generated by tools/redirect-bridges.mjs -->';
const CLEAN = process.argv.includes('--clean');

/**
 * The .html paths that really existed before the 20 Aug 2026 migration, and that
 * Google therefore still has indexed. This list is historical and closed: hub pages
 * such as /blog/ were always directories and never had a .html form, so bridging
 * them would invent a .html URL that never existed.
 */
const LEGACY_HTML_PATHS = [
  'blog/clipping-agency-vs-hiring-an-editor.html',
  'blog/does-clipping-work.html',
  'blog/emrah-bayraktar-vision-clipping-press.html',
  'blog/how-much-does-a-clipping-agency-cost.html',
  'blog/how-much-does-a-clipping-campaign-cost.html',
  'blog/how-to-build-a-founder-brand.html',
  'blog/how-to-choose-the-best-clipping-agency.html',
  'blog/how-to-repurpose-long-form-content.html',
  'blog/is-clipping-a-scam.html',
  'blog/is-clipping-expensive.html',
  'blog/is-clipping-mass-manipulation.html',
  'blog/mass-clipping-campaign-vs-internal-clipping-campaign.html',
  'blog/the-clipping-economy-explained.html',
  'blog/thought-leadership-is-a-distribution-problem.html',
  'blog/what-is-content-clipping.html',
  'blog/why-build-your-clipping-team-in-house.html',
  'blog/why-you-should-do-mass-clipping.html',
  'breakdowns/andrew-tate-clipping.html',
  'breakdowns/diary-of-a-ceo-clipping.html',
  'breakdowns/iman-gadzhi-clipping.html',
  'breakdowns/joe-rogan-clips.html',
  'breakdowns/luke-belmar-clipping.html',
  'breakdowns/music-clipping.html',
  'breakdowns/polymarket-clipping.html',
  'breakdowns/stake-clipping.html',
  'cases/arab.html',
  'cases/iman-gadzhi.html',
  'cases/luke-belmar.html',
  'cases/nonstop.html',
  'cases/russell-brunson.html',
  'content-repurposing-agency.html',
  'fr/blog/clipping-agency-vs-hiring-an-editor.html',
  'fr/blog/does-clipping-work.html',
  'fr/blog/emrah-bayraktar-vision-clipping-press.html',
  'fr/blog/how-much-does-a-clipping-agency-cost.html',
  'fr/blog/how-much-does-a-clipping-campaign-cost.html',
  'fr/blog/how-to-build-a-founder-brand.html',
  'fr/blog/how-to-choose-the-best-clipping-agency.html',
  'fr/blog/how-to-repurpose-long-form-content.html',
  'fr/blog/is-clipping-a-scam.html',
  'fr/blog/is-clipping-expensive.html',
  'fr/blog/mass-clipping-campaign-vs-internal-clipping-campaign.html',
  'fr/blog/the-clipping-economy-explained.html',
  'fr/blog/thought-leadership-is-a-distribution-problem.html',
  'fr/blog/what-is-content-clipping.html',
  'fr/blog/why-build-your-clipping-team-in-house.html',
  'fr/blog/why-you-should-do-mass-clipping.html',
  'nl/blog/clipping-agency-vs-hiring-an-editor.html',
  'nl/blog/does-clipping-work.html',
  'nl/blog/emrah-bayraktar-vision-clipping-press.html',
  'nl/blog/how-much-does-a-clipping-agency-cost.html',
  'nl/blog/how-much-does-a-clipping-campaign-cost.html',
  'nl/blog/how-to-build-a-founder-brand.html',
  'nl/blog/how-to-choose-the-best-clipping-agency.html',
  'nl/blog/how-to-repurpose-long-form-content.html',
  'nl/blog/is-clipping-a-scam.html',
  'nl/blog/is-clipping-expensive.html',
  'nl/blog/mass-clipping-campaign-vs-internal-clipping-campaign.html',
  'nl/blog/the-clipping-economy-explained.html',
  'nl/blog/thought-leadership-is-a-distribution-problem.html',
  'nl/blog/what-is-content-clipping.html',
  'nl/blog/why-build-your-clipping-team-in-house.html',
  'nl/blog/why-you-should-do-mass-clipping.html',
  'podcast-clipping-service.html',
  'tr/blog/clipping-agency-vs-hiring-an-editor.html',
  'tr/blog/does-clipping-work.html',
  'tr/blog/emrah-bayraktar-vision-clipping-press.html',
  'tr/blog/how-much-does-a-clipping-agency-cost.html',
  'tr/blog/how-much-does-a-clipping-campaign-cost.html',
  'tr/blog/how-to-build-a-founder-brand.html',
  'tr/blog/how-to-choose-the-best-clipping-agency.html',
  'tr/blog/how-to-repurpose-long-form-content.html',
  'tr/blog/is-clipping-a-scam.html',
  'tr/blog/is-clipping-expensive.html',
  'tr/blog/mass-clipping-campaign-vs-internal-clipping-campaign.html',
  'tr/blog/the-clipping-economy-explained.html',
  'tr/blog/thought-leadership-is-a-distribution-problem.html',
  'tr/blog/what-is-content-clipping.html',
  'tr/blog/why-build-your-clipping-team-in-house.html',
  'tr/blog/why-you-should-do-mass-clipping.html',
];

function bridge(url) {
  return `<!doctype html>
<html lang="en">
${MARKER}
<head>
<meta charset="utf-8">
<title>Redirecting to ${url}</title>
<link rel="canonical" href="${url}">
<meta http-equiv="refresh" content="0; url=${url}">
<script>location.replace(${JSON.stringify(url)});</script>
</head>
<body>
<p>This page has moved to <a href="${url}">${url}</a>.</p>
</body>
</html>
`;
}

let written = 0, removed = 0;
for (const legacy of LEGACY_HTML_PATHS) {
  const dir = legacy.slice(0, -'.html'.length); // blog/foo
  const oldPath = join(ROOT, legacy);           // blog/foo.html
  const url = `${SITE}/${dir}/`;

  if (CLEAN) {
    if (existsSync(oldPath) && readFileSync(oldPath, 'utf8').includes(MARKER)) {
      unlinkSync(oldPath);
      removed++;
    }
    continue;
  }
  // never overwrite a real page that happens to sit at this path
  if (existsSync(oldPath) && !readFileSync(oldPath, 'utf8').includes(MARKER)) {
    console.warn(`  skip (real page, not a bridge): ${dir}.html`);
    continue;
  }
  writeFileSync(oldPath, bridge(url));
  written++;
}
console.log(CLEAN ? `removed ${removed} bridges` : `wrote ${written} redirect bridges`);
